### ISSUE TITLE
Conflict with ocramius/package-versions

### ISSUE THREAD

**Issue by cherifGsoul** [chubbyphp/chubbyphp-laminas-config-doctrine#2]
In Mezzio (installed using skeleton), `ocramius/package-versions` package causes a conflict, maybe the version should be updated in the line https://github.com/chubbyphp/chubbyphp-laminas-config-doctrine/blob/afaea6e06d9ef819ca2b153cc1b8a32c955c127e/composer.json#L54

**Comment by dominikzogg** [comment]
@cherifGsoul  sorry for the late response, i misconfigured the notifications. Please try the newest minor upgrade

**Comment by cherifGsoul** [comment]
No worries @dominikzogg , thank you for the fix!

**Comment by dominikzogg** [comment]
@cherifGsoul you're welcome
